name: Terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init Dev Environment
        run: terraform init -reconfigure
        working-directory: ./terraform/dev

      - name: Terraform Format Dev Environment
        run: terraform fmt -check
        working-directory: ./terraform/dev

      - name: Terraform Validate Dev Environment
        run: terraform validate
        working-directory: ./terraform/dev

      - name: Terraform Plan Dev Environment
        run: terraform plan -input=false
        working-directory: ./terraform/dev

  apply:
    name: Terraform Apply
    needs: plan
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init Dev Environment
        run: terraform init -reconfigure
        working-directory: ./terraform/dev

      - name: Terraform Apply Dev Environment
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform/dev